import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { git, showFile, tagRef } from "./git.js";
import { mergeFile, type FileMerge } from "./merge.js";
import type { Step } from "./tags.js";

/**
 * Planning a review: which files a base -> target range touches, which of
 * them are reviewed and which are simply taken from the target, and the
 * commands to run first. A range may be one step (03 -> 04), several (02 ->
 * 05), or cross a workshop boundary; it is just two positions in the line.
 */

export type FileStatus = "added" | "modified" | "deleted" | "renamed";

export interface ReviewFile {
  /** Path at the target (for a delete, the path that goes away). */
  path: string;
  /** Path at the base, set only for a rename. */
  oldPath: string | undefined;
  status: FileStatus;
}

export interface TargetFile extends ReviewFile {
  reason: "lockfile" | "binary";
}

export interface ReviewPlan {
  base: Step;
  target: Step;
  /** Steps after the base up to and including the target, in order. */
  steps: Step[];
  /** `Run:` commands of every step in the range, in order. */
  commands: string[];
  /** Text files to merge and review. */
  files: ReviewFile[];
  /** Lockfiles and binaries: not reviewed, copied from the target. */
  fromTarget: TargetFile[];
}

/** Lockfiles are regenerated by the step's install command, never merged. */
export const LOCKFILES: ReadonlySet<string> = new Set([
  "pnpm-lock.yaml",
  "pubspec.lock",
  "package-lock.json",
  "yarn.lock",
]);

export function isLockfile(path: string): boolean {
  return LOCKFILES.has(path.slice(path.lastIndexOf("/") + 1));
}

interface DiffEntry extends ReviewFile {
  binary: boolean;
}

/**
 * `git diff --name-status -M` between two tags, with `--numstat` alongside
 * to spot binaries (`-` counts). `-z` keeps odd file names intact.
 */
export async function diffTags(
  cwd: string,
  baseTag: string,
  targetTag: string,
): Promise<ReviewFile[]> {
  return (await diffEntries(cwd, baseTag, targetTag)).map(
    ({ binary: _b, ...file }) => file,
  );
}

async function diffEntries(
  cwd: string,
  baseTag: string,
  targetTag: string,
): Promise<DiffEntry[]> {
  const refs = ["--end-of-options", tagRef(baseTag), tagRef(targetTag)];
  const [nameStatus, numstat] = await Promise.all([
    git(cwd, ["diff", "--name-status", "-M", "-z", ...refs]),
    git(cwd, ["diff", "--numstat", "-M", "-z", ...refs]),
  ]);

  // Binary paths, keyed by the target-side path.
  const binaries = new Set<string>();
  const stat = numstat.split("\0");
  for (let i = 0; i < stat.length; i++) {
    const head = stat[i]!;
    if (head === "") continue;
    const [added, deleted, path] = head.split("\t");
    const isBinary = added === "-" && deleted === "-";
    if (path === "") {
      // A rename: the old and new paths follow as separate NUL fields.
      const next = stat[i + 2];
      if (isBinary && next) binaries.add(next);
      i += 2;
    } else if (isBinary && path) {
      binaries.add(path);
    }
  }

  const entries: DiffEntry[] = [];
  const fields = nameStatus.split("\0");
  for (let i = 0; i < fields.length; i++) {
    const code = fields[i]!;
    if (code === "") continue;
    const letter = code[0];
    if (letter === "R" || letter === "C") {
      const oldPath = fields[i + 1]!;
      const path = fields[i + 2]!;
      i += 2;
      entries.push({
        path,
        oldPath,
        status: "renamed",
        binary: binaries.has(path),
      });
      continue;
    }
    const path = fields[++i]!;
    const status: FileStatus =
      letter === "A" ? "added" : letter === "D" ? "deleted" : "modified";
    entries.push({
      path,
      oldPath: undefined,
      status,
      binary: binaries.has(path),
    });
  }
  return entries;
}

/**
 * Plans a review from `base` to `target`, both steps of `line`. The base is
 * the last step the attendee has, or `00-start` when they have none.
 */
export async function planReview(
  cwd: string,
  line: readonly Step[],
  base: Step,
  target: Step,
): Promise<ReviewPlan> {
  const baseIndex = line.findIndex((s) => s.tag === base.tag);
  const targetIndex = line.findIndex((s) => s.tag === target.tag);
  if (baseIndex < 0 || targetIndex < 0) {
    throw new Error(
      `Step not in the line: ${baseIndex < 0 ? base.tag : target.tag}`,
    );
  }
  if (baseIndex >= targetIndex) {
    throw new Error(`${base.tag} is not before ${target.tag}`);
  }

  const steps = line.slice(baseIndex + 1, targetIndex + 1);
  const files: ReviewFile[] = [];
  const fromTarget: TargetFile[] = [];
  for (const { binary, ...file } of await diffEntries(
    cwd,
    base.tag,
    target.tag,
  )) {
    if (isLockfile(file.path)) fromTarget.push({ ...file, reason: "lockfile" });
    else if (binary) fromTarget.push({ ...file, reason: "binary" });
    else files.push(file);
  }
  return {
    base,
    target,
    steps,
    commands: steps.flatMap((s) => s.run),
    files,
    fromTarget,
  };
}

/** Bytes look binary if they contain a NUL, the same test git uses. */
export function looksBinary(bytes: Buffer): boolean {
  return bytes.subarray(0, 8000).includes(0);
}

async function readWorkingFile(
  root: string,
  path: string,
): Promise<Buffer | null> {
  try {
    return await readFile(join(root, path));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    if ((error as NodeJS.ErrnoException).code === "EISDIR") return null;
    throw error;
  }
}

/**
 * Builds the three-way merge for one reviewed file: base and target come
 * from `git show <tag>:<path>`, ours is the working-tree file. A rename reads
 * ours from the new path if they already have it, else from the old one.
 *
 * `root` is the repo's top level (paths from `git diff` are relative to it).
 * Returns null when a side turns out to be binary; the caller then takes the
 * target's copy like any other unreviewed file.
 */
export async function loadFileMerge(
  root: string,
  plan: Pick<ReviewPlan, "base" | "target">,
  file: ReviewFile,
): Promise<FileMerge | null> {
  const baseBytes = await showFile(
    root,
    tagRef(plan.base.tag),
    file.oldPath ?? file.path,
  );
  const theirsBytes = await showFile(root, tagRef(plan.target.tag), file.path);
  let oursBytes = await readWorkingFile(root, file.path);
  if (oursBytes === null && file.oldPath)
    oursBytes = await readWorkingFile(root, file.oldPath);

  if (
    [baseBytes, oursBytes, theirsBytes].some(
      (b) => b !== null && looksBinary(b),
    )
  ) {
    return null;
  }
  const text = (b: Buffer | null) => (b === null ? null : b.toString("utf8"));
  return mergeFile({
    base: text(baseBytes),
    ours: text(oursBytes),
    theirs: text(theirsBytes),
  });
}
