/**
 * Generates the build-time inputs `src/` imports (`pnpm codegen`, run
 * automatically before build, typecheck, lint and test; gitignored):
 *
 *   * `src/generated/assets.ts`: the logo artwork in `artwork/`, split and
 *     embedded as `<img>` data URIs.
 *   * `src/generated/icons.ts`: the Phosphor bold icon paths the templates draw.
 *   * `palette.css`: the palette as CSS variables, for consumers' stylesheets.
 *
 * Everything is derived from this package, so it is deterministic and needs no
 * network. (The fonts are fetched, not derived: see `fetch-fonts.ts`.)
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type ComponentType, createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as Phosphor from "@phosphor-icons/react/ssr";
import { paletteCss } from "../src/palette.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "src", "generated");
const BRAND = path.join(HERE, "..", "artwork");
const BANNER = `// @generated by scripts/codegen.ts — do not edit by hand.\n// Regenerated automatically by \`pnpm codegen\`; gitignored.\n`;

/* ----------------------------------------------------------------- assets */

/** An `<img src>` Satori can draw, plus the aspect ratio to size it by. */
function dataUri(svg: string) {
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}

function svgAttrs(svg: string) {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error("asset has no viewBox");
  const [, , w, h] = viewBox.split(/\s+/).map(Number) as [
    number,
    number,
    number,
    number,
  ];
  return { width: w, height: h };
}

/**
 * Where each half of the lockup actually is, in the file's own units.
 *
 * `devdogs-logo-dark.svg` has one viewBox around both marks, so cropping to
 * either one means naming its box. These are the rendered ink bounds, measured
 * once at 40x and rounded in — not the artboard, which carries whitespace on
 * every side and would make "set the mascot to 384px" mean 384px of dog *plus*
 * however much padding the export happened to leave.
 *
 * They are constants rather than something this script derives because
 * measuring them needs a rasteriser, and pulling one in to re-learn four
 * numbers that change only when the logo does is a poor trade. The path-count
 * assertion in `splitLockup` is the guard that matters: it fails loudly if the
 * file is re-exported into a different shape, which is the only way these can
 * silently stop being true.
 */
const MASCOT_BOX = [0, 0, 28.15, 30.05] as const;
const WORDMARK_BOX = [37.35, 8.875, 74.05, 16.1] as const;

/**
 * Splits the combined lockup into the two marks the templates place
 * independently.
 *
 * `devdogs-logo-dark.svg` is one file holding both: 51 paths of mascot followed
 * by a single path of "DevDogs" wordmark. Every layout here sizes the two
 * against each other — the wide banner sets the mascot at 384px and the wordmark
 * at 112 — so they cannot come from one image. The split is by path index and
 * asserted on, because a re-export from the design tool that reorders or
 * re-segments the file would otherwise put half a dog in the wordmark slot.
 */
function splitLockup(file: string) {
  const svg = readFileSync(path.join(BRAND, file), "utf8");
  const paths = svg.match(/<path\b[^>]*\/>/g) ?? [];
  if (paths.length !== 52) {
    throw new Error(
      `${file}: expected 52 paths (51 mascot + 1 wordmark), got ${paths.length}`,
    );
  }

  const crop = (
    body: string,
    box: readonly [number, number, number, number],
  ) => ({
    svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box[0]} ${box[1]} ${box[2]} ${box[3]}">${body}</svg>`,
    box: { width: box[2], height: box[3] },
  });

  return {
    mark: crop(paths.slice(0, 51).join(""), MASCOT_BOX),
    wordmark: crop(paths[51]!, WORDMARK_BOX),
  };
}

function assets() {
  const dark = splitLockup("devdogs-logo-dark.svg");
  const light = splitLockup("devdogs-logo.svg");

  const gdgc = readFileSync(
    path.join(BRAND, "gdgc-uga-lockup-dark.svg"),
    "utf8",
  );
  const gdgMark = readFileSync(path.join(BRAND, "gdg-bracket.svg"), "utf8");

  /**
   * The same lockup for a light ground.
   *
   * The checked-in file is the dark-ground variant: "Google Developer Groups"
   * and "UGA" are white, so on a white ground the chevron and the blue "On
   * Campus" float over nothing. Only the neutral ink changes — Google's four
   * chevron colours and the blue belong to the mark and are left alone.
   *
   * `#636d74` is not a guess at a Google grey. It is sampled from the club's
   * own copy of the lockup at
   * the schedule builder's `public/images/GoogleDevLogo.png`, which is what the
   * UGA chapter actually publishes.
   */
  const gdgcLight = gdgc.replace(/fill="(white|#FFFFFF)"/gi, 'fill="#636d74"');

  const decls: string[] = [];
  const add = (
    decls: string[],
    name: string,
    svg: string,
    box: { width: number; height: number },
    doc: string,
  ) => {
    decls.push(
      `/** ${doc} */\nexport const ${name}: Asset = {\n  src: "${dataUri(svg)}",\n  width: ${box.width},\n  height: ${box.height},\n};`,
    );
  };

  add(
    decls,
    "MARK",
    dark.mark.svg,
    dark.mark.box,
    "The mascot alone. Full colour, and legible on any ground dark enough to hold the site's own background.",
  );
  add(
    decls,
    "WORDMARK_ON_DARK",
    dark.wordmark.svg,
    dark.wordmark.box,
    'The "DevDogs" wordmark in white, cropped to its own ink.',
  );
  add(
    decls,
    "WORDMARK_ON_LIGHT",
    light.wordmark.svg,
    light.wordmark.box,
    "The same wordmark in black, for the light grounds email bodies use.",
  );
  // The whole lockup, mascot and wordmark in one image, as the newsletter
  // masthead and footers set it.
  for (const [name, file, ground] of [
    ["LOCKUP_ON_DARK", "devdogs-logo-dark.svg", "dark"],
    ["LOCKUP_ON_LIGHT", "devdogs-logo.svg", "light"],
  ] as const) {
    const svg = readFileSync(path.join(BRAND, file), "utf8").trim();
    add(
      decls,
      name,
      svg,
      svgAttrs(svg),
      `The mascot and wordmark as one lockup, drawn for ${ground} grounds.`,
    );
  }
  add(
    decls,
    "GDG_MARK",
    gdgMark,
    svgAttrs(gdgMark),
    "The official Google Developer Groups bracket mark, downloaded unchanged from developers.google.com.",
  );
  add(
    decls,
    "GDGC_UGA",
    gdgc,
    svgAttrs(gdgc),
    "The GDG on Campus · UGA chapter lockup, for dark grounds. Rebuilt as vector from Google's official chevron and wordmark.",
  );
  add(
    decls,
    "GDGC_UGA_LIGHT",
    gdgcLight,
    svgAttrs(gdgc),
    "The same chapter lockup with its neutral ink darkened, for light grounds.",
  );

  const assetInterface = `/**
 * A brand mark as an \`<img>\` source.
 *
 * \`width\`/\`height\` are the artwork's own units, carried so a template can set
 * one dimension and derive the other rather than hard-coding an aspect ratio
 * that goes stale when the artwork is re-exported.
 */
export interface Asset {
  src: string;
  width: number;
  height: number;
}`;

  writeFileSync(
    path.join(OUT, "assets.ts"),
    `${BANNER}
${assetInterface}

${decls.join("\n\n")}
`,
  );
}

/* ------------------------------------------------------------------ icons */

/**
 * The Phosphor marks the templates use, taken from the same package the app
 * draws its UI with so the two cannot diverge.
 *
 * Bold weight throughout: these sit next to display type at sizes where the
 * regular weight's hairlines disappear, and the site's own visual language is
 * heavy strokes. Rendered through Phosphor's SSR entry and scraped for path
 * data rather than pattern-matched out of its source, which is minified and
 * free to change shape between releases.
 */
const ICONS = {
  Globe: "the website line",
  InstagramLogo: "socials",
  LinkedinLogo: "socials",
  GithubLogo: "socials",
  CalendarDot: "an event's date",
  Clock: "an event's hours",
  MapPin: "where an event is",
  UsersThree: "the community page",
  EnvelopeSimple: "the email signature",
} as const;

function icons() {
  const decls: string[] = [];

  for (const [name, why] of Object.entries(ICONS)) {
    // Phosphor exports each mark twice, bare and `-Icon` suffixed, and which
    // of the two exists has moved between releases. Try the suffixed name the
    // app's `config/icons.ts` imports, then the bare one.
    const exports = Phosphor as Record<
      string,
      ComponentType<{ weight: string }> | undefined
    >;
    const Icon = exports[`${name}Icon`] ?? exports[name];
    if (!Icon) throw new Error(`@phosphor-icons/react/ssr has no ${name}`);

    // `createElement` rather than calling the component: these are wrapped in
    // `forwardRef`, so they are objects React can render and not functions
    // anything can invoke.
    const markup = renderToStaticMarkup(
      createElement(Icon, { weight: "bold" }),
    );
    const paths = [...markup.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]!);
    if (paths.length === 0) throw new Error(`${name} rendered no paths`);

    decls.push(
      `  /** Phosphor \`${name}\`, bold — ${why}. */\n  ${name}: [\n${paths.map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ],`,
    );
  }

  writeFileSync(
    path.join(OUT, "icons.ts"),
    `${BANNER}
/**
 * Path data only, on Phosphor's 256-unit grid. The templates wrap these in
 * their own \`<svg>\` so the fill is the caller's to choose — which is the whole
 * reason these are paths here and not \`<img>\` data URIs like the brand marks.
 */
export const ICON_PATHS = {
${decls.join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`,
  );
}

/* ---------------------------------------------------------------- palette */

writeFileSync(path.join(HERE, "..", "palette.css"), paletteCss());

/* ------------------------------------------------------------------- main */

mkdirSync(OUT, { recursive: true });
assets();
icons();
