/**
 * Fetches the club's brand fonts from Google Fonts into the committed
 * `src/generated/fonts.ts` (`pnpm fetch:fonts`).
 *
 * Run it by hand when a face changes; the output is committed. It is not part
 * of `build` on purpose: it reaches out to Google Fonts, and a network
 * dependency in `build` would fail CI for reasons that have nothing to do with
 * the commit under test.
 *
 * The faces are *embedded*, base64 in a TypeScript module rather than a file
 * read at render time. The platform renders these templates inside a
 * Cloudflare Worker, where there is no filesystem to read a .ttf out of and a
 * runtime fetch would add a network round trip, and a way to fail, to every
 * link unfurl.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "src", "generated");
const BANNER_FOR_BRAND = `// @generated by scripts/fetch-fonts.ts — do not edit by hand.\n// Run \`pnpm fetch:fonts\` in packages/brand to refresh.\n`;

/* ------------------------------------------------------------------ fonts */

/**
 * The faces the templates set type in, and nothing else.
 *
 * Three rather than the site's full range, because every one is carried in the
 * Worker bundle: Hanken Grotesk at 400 and 700 covers body copy and its
 * emphasis, and Alan Sans at 800 is the display weight the headings use. Satori
 * picks a face by exact weight and does not synthesise the ones in between, so
 * a template asking for 600 silently lands on 400 — the templates only ask for
 * these three.
 */
const FACES = [
  { family: "Hanken Grotesk", weight: 400 },
  { family: "Hanken Grotesk", weight: 700 },
  { family: "Alan Sans", weight: 800 },
] as const;

async function fonts() {
  const families = [...new Set(FACES.map((f) => f.family))]
    .map((family) => {
      const weights = FACES.filter((f) => f.family === family).map(
        (f) => f.weight,
      );
      return `family=${family.replace(/ /g, "+")}:wght@${weights.join(";")}`;
    })
    .join("&");

  // The stylesheet Google serves is content-negotiated on User-Agent. With a
  // modern one it answers woff2, which Satori cannot parse (it reads ttf, otf
  // and woff); with none it answers plain TrueType. So: send none, and assert
  // on the format rather than trusting that to stay true.
  const css = await fetch(`https://fonts.googleapis.com/css2?${families}`).then(
    (r) => {
      if (!r.ok) throw new Error(`Google Fonts answered ${r.status}`);
      return r.text();
    },
  );

  const faces = [
    ...css.matchAll(
      /font-family: '([^']+)';[\s\S]*?font-weight: (\d+);[\s\S]*?src: url\((\S+?)\) format\('truetype'\)/g,
    ),
  ];

  const found = new Map(faces.map((m) => [`${m[1]}@${m[2]}`, m[3]!]));
  const entries: string[] = [];

  for (const { family, weight } of FACES) {
    const url = found.get(`${family}@${weight}`);
    if (!url)
      throw new Error(`Google Fonts returned no truetype ${family} ${weight}`);

    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} answered ${response.status}`);
    const buf = Buffer.from(await response.arrayBuffer());
    // "true" and 0x00010000 are the two legal TrueType magic numbers; anything
    // else means the negotiation above drifted back to woff2 and every render
    // would fall through to Satori's own fallback face.
    const magic = buf.readUInt32BE(0);
    if (magic !== 0x00010000 && buf.subarray(0, 4).toString() !== "true") {
      throw new Error(
        `${family} ${weight} is not TrueType (magic ${magic.toString(16)})`,
      );
    }

    console.log(`  ${family} ${weight}: ${(buf.length / 1024).toFixed(1)} KB`);
    entries.push(
      `  {\n    name: ${JSON.stringify(family)},\n    weight: ${weight},\n    style: "normal",\n    data: "${buf.toString("base64")}",\n  },`,
    );
  }

  writeFileSync(
    path.join(OUT, "fonts.ts"),
    `${BANNER_FOR_BRAND}
/** A face as Satori wants it, with the payload still base64. */
export interface EmbeddedFont {
  name: string;
  weight: 400 | 700 | 800;
  style: "normal";
  data: string;
}

export const EMBEDDED_FONTS: EmbeddedFont[] = [
${entries.join("\n")}
];
`,
  );
}

mkdirSync(OUT, { recursive: true });
console.log("fonts:");
await fonts();
