import { ACCENT, MAUVE, THEME, WHITE } from "./brand.js";

/**
 * The palette flattened to `name -> #rrggbb`.
 *
 * For the places that cannot read the OKLCH the app declares its colours in,
 * or cannot read a stylesheet at all: email HTML, Satori, a Vue theme. Names
 * are the CSS variable names without the `--brand-` prefix, so
 * `PALETTE["mauve-950"]` is `--brand-mauve-950` in {@link paletteCss}.
 */
export const PALETTE: Readonly<Record<string, string>> = {
  ...Object.fromEntries(
    Object.entries(MAUVE).map(([step, hex]) => [`mauve-${step}`, hex]),
  ),
  red400: ACCENT.red400,
  red700: ACCENT.red700,
  purple400: ACCENT.purple400,
  purple700: ACCENT.purple700,
  cyan400: ACCENT.cyan400,
  amber400: ACCENT.amber400,
  emerald400: ACCENT.emerald400,
  white: WHITE,
  ink: THEME.ink,
};

/** Kebab-cases an accent key: `red400` is `red-400`. */
const cssName = (name: string) => name.replace(/([a-z])(\d)/, "$1-$2");

/**
 * The palette as a stylesheet of CSS custom properties, `--brand-<name>`.
 *
 * The same string is written to `@devdogsuga/brand/palette.css` at build, so
 * platform, schedule-builder, slides and the email package take the values
 * from there instead of copying hex.
 */
export function paletteCss(): string {
  const lines = Object.entries(PALETTE).map(
    ([name, hex]) => `  --brand-${cssName(name)}: ${hex};`,
  );
  return `/* @generated by @devdogsuga/brand — the club palette as CSS variables. */\n:root {\n${lines.join("\n")}\n}\n`;
}
