import { describe, expect, it, vi } from "vitest";
import { parseItem, type BwItem } from "./item.js";
import { renderReport, resolveLinearToken, writeReport } from "./report.js";

const item = (name: string, fields: BwItem["fields"]): BwItem => ({
  id: name,
  organizationId: "org",
  collectionIds: ["col"],
  name,
  notes: null,
  type: 1,
  login: {
    username: `${name.toLowerCase()}-login`,
    password: "pw-secret-value",
    totp: null,
  },
  fields,
});

describe("the Shared Accounts document", () => {
  const now = new Date("2026-10-05T12:00:00Z");
  const content = renderReport(
    [
      parseItem(
        item("Instagram", [
          { name: "Recipients", value: "a@uga.edu", type: 0 },
          { name: "Owner", value: "Sloan", type: 0 },
          { name: "Send ID", value: "s1", type: 0 },
          {
            name: "Send link",
            value: "https://send.bitwarden.com/#a/b",
            type: 0,
          },
          { name: "Send expires", value: "2026-10-09T00:00:00.000Z", type: 0 },
        ]),
      ),
      parseItem(item("Linktree", [])),
    ],
    now,
    {
      officers: [{ name: "Ada", email: "a@uga.edu", roles: ["President"] }],
      roles: [],
    },
  );

  it("says it is generated and overwritten", () => {
    expect(content).toMatch(/^> Generated by `backstage creds`/);
    expect(content).toContain("Manual edits are overwritten");
  });

  it("has a row per account, with status, expiry and link", () => {
    expect(content).toContain(
      "| Instagram | instagram-login | Ada <a@uga.edu> | Sloan | Expires Soon | 2026-10-09 | [Open](https://send.bitwarden.com/#a/b) |",
    );
    expect(content).toContain(
      "| Linktree | linktree-login | — | — | No Send | — | — |",
    );
  });

  it("never holds a password", () => {
    expect(content).not.toContain("pw-secret-value");
  });
});

describe("the Linear key", () => {
  it("prefers the flag, then LINEAR_API_KEY, then the vault, then a prompt", async () => {
    const vault = vi.fn(async () => "lin_vault");
    const prompt = vi.fn(async () => "lin_prompt");
    expect(
      await resolveLinearToken({
        explicit: "lin_flag",
        env: "lin_env",
        fromVault: vault,
        prompt,
      }),
    ).toBe("lin_flag");
    expect(
      await resolveLinearToken({ env: "lin_env", fromVault: vault, prompt }),
    ).toBe("lin_env");
    expect(await resolveLinearToken({ fromVault: vault, prompt })).toBe(
      "lin_vault",
    );
    expect(
      await resolveLinearToken({ fromVault: async () => undefined, prompt }),
    ).toBe("lin_prompt");
    expect(vault).toHaveBeenCalledTimes(1);
  });
});

describe("writing the document", () => {
  it("replaces the content with documentUpdate, authorized by the key", async () => {
    const fetchImpl = vi.fn(
      async (_url: string | URL | Request, init?: RequestInit) => {
        const body = JSON.parse(init?.body as string) as {
          variables: { id: string; input: { content: string } };
        };
        expect(body.variables).toEqual({
          id: "doc-1",
          input: { content: "# hi" },
        });
        expect((init?.headers as Record<string, string>).Authorization).toBe(
          "lin_key",
        );
        return new Response(
          JSON.stringify({
            data: {
              documentUpdate: {
                success: true,
                document: { url: "https://linear.app/d" },
              },
            },
          }),
        );
      },
    );
    expect(await writeReport("lin_key", "doc-1", "# hi", fetchImpl)).toBe(
      "https://linear.app/d",
    );
  });

  it("names Linear's reason when it refuses", async () => {
    const fetchImpl = vi.fn(
      async () =>
        new Response(
          JSON.stringify({ errors: [{ message: "Entity not found" }] }),
          {
            status: 400,
          },
        ),
    );
    await expect(
      writeReport("lin_key", "doc-1", "x", fetchImpl),
    ).rejects.toThrow(/Entity not found/);
  });
});
