/**
 * The **Shared Accounts** Linear document: who has which shared login, until
 * when, and the link to send them back to.
 *
 * Generated whole on every `send`, `add`, `renew` and `report` from the
 * organization items that have recipients or a Send, and written over the
 * document by id. It is a report, not a
 * record: the record is the item fields (`item.ts`), so an edit made here is
 * overwritten and the header says so.
 *
 * Officers are the audience, and only officers have Linear. Even so it holds
 * no secret values: names, usernames, addresses, dates and Send links, each
 * of which opens only for the addresses Bitwarden verifies.
 */
import { password as askPassword } from "@clack/prompts";
import { nonEmpty } from "@devdogsuga/cli-core/db/connection";
import { unwrap } from "@devdogsuga/cli-core/ui";
import { readPasswordFromVault } from "../bws/vault.js";
import { isoDay, sendStatus, type SharedItem } from "./item.js";
import { describeRecipient, type Roster } from "./roster.js";
import { CredsError, registerSecret } from "./secrets.js";

/** The document, attached to the Platform & DevOps initiative. Created 2026-10-01. */
export const SHARED_ACCOUNTS_DOCUMENT_ID =
  "209799db-5981-4796-a41e-2bb433020d06";

export const LINEAR_VAULT_ITEM = "DevDogs Linear API key (backstage)";

const LINEAR_API = "https://api.linear.app/graphql";

function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/** The document's markdown. Pure: `now` decides the statuses. */
export function renderReport(
  items: readonly SharedItem[],
  now: Date,
  roster?: Roster,
): string {
  const lines = [
    "> Generated by `backstage creds` from the DevDogs Bitwarden organization: every item shared as a Send. " +
      "Manual edits are overwritten on the next run; change the item's fields in Bitwarden, or run `backstage creds send`.",
    "",
    `Last generated ${now.toISOString().slice(0, 16).replace("T", " ")} UTC. ` +
      "Sends are deleted 30 days after they were last renewed; " +
      "**Expires Soon** means within 7 days, so run `backstage creds renew`.",
    "",
  ];
  // Only what has been shared: the organization holds more than it hands out.
  const shared = items.filter(
    (i) => i.recipients.length > 0 || i.send !== undefined,
  );
  if (shared.length === 0) {
    lines.push("Nothing has been shared yet.");
    return `${lines.join("\n")}\n`;
  }
  lines.push(
    "| Credential | Account | Recipients | Owner | Status | Expires | Send |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const item of shared) {
    const recipients =
      item.recipients.length > 0
        ? item.recipients.map((e) => describeRecipient(roster, e)).join(", ")
        : "—";
    const link = item.send?.link ? `[Open](${item.send.link})` : "—";
    lines.push(
      `| ${[
        cell(item.name),
        cell(item.username ?? "—"),
        cell(recipients),
        cell(item.owner ?? "—"),
        sendStatus(item, now),
        isoDay(item.send?.expires),
        link,
      ].join(" | ")} |`,
    );
  }
  return `${lines.join("\n")}\n`;
}

export interface LinearTokenSources {
  explicit?: string;
  env?: string;
  fromVault?: () => Promise<string | undefined>;
  prompt?: () => Promise<string | undefined>;
}

/**
 * `--linear-token`, then `LINEAR_API_KEY`, then the vault item, then a prompt.
 * Never saved anywhere: the vault is where it lives.
 */
export async function resolveLinearToken(
  sources: LinearTokenSources,
): Promise<string> {
  const token =
    nonEmpty(sources.explicit) ??
    nonEmpty(sources.env) ??
    (await (sources.fromVault ?? readLinearTokenFromVault)()) ??
    (await (sources.prompt ?? promptForLinearToken)());
  if (!token) {
    throw new CredsError(
      `No Linear API key. Set LINEAR_API_KEY, or store one in your vault as "${LINEAR_VAULT_ITEM}".`,
    );
  }
  registerSecret(token);
  return token;
}

function readLinearTokenFromVault(): Promise<string | undefined> {
  return readPasswordFromVault(
    LINEAR_VAULT_ITEM,
    "the Linear API key",
    "read the Linear API key",
    "LINEAR_API_KEY",
  );
}

async function promptForLinearToken(): Promise<string | undefined> {
  if (!process.stdin.isTTY) return undefined;
  const value = unwrap(
    await askPassword({
      message: "Linear API key? (Settings → Security & access → API keys)",
    }),
  );
  return nonEmpty(value.trim());
}

export type Fetch = typeof fetch;

/** Replaces the document's content. Returns its URL. */
export async function writeReport(
  token: string,
  documentId: string,
  content: string,
  fetchImpl: Fetch = fetch,
): Promise<string> {
  let response: Response;
  try {
    response = await fetchImpl(LINEAR_API, {
      method: "POST",
      headers: { Authorization: token, "Content-Type": "application/json" },
      body: JSON.stringify({
        query:
          "mutation($id: String!, $input: DocumentUpdateInput!) { documentUpdate(id: $id, input: $input) { success document { url } } }",
        variables: { id: documentId, input: { content } },
      }),
    });
  } catch (err) {
    throw new CredsError(
      `Could not reach Linear: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  const payload = (await response.json().catch(() => ({}))) as {
    data?: {
      documentUpdate?: { success: boolean; document?: { url?: string } };
    };
    errors?: { message: string }[];
  };
  const result = payload.data?.documentUpdate;
  if (!response.ok || !result?.success) {
    const why =
      payload.errors?.map((e) => e.message).join("; ") ??
      `HTTP ${response.status}`;
    throw new CredsError(`Linear refused the Shared Accounts update: ${why}`);
  }
  return result.document?.url ?? documentId;
}
